
def plural(value, count=2):
    '''
    Usage: 
            {{ var|plural }}
            {{ var|plural:count }}
            
            If [count] > 1 or [count] is not specified, the filter returns the plural form of [var].
            Plural form is generated by sequentially applying the following rules:
                * convert 'y' at the end into 'ie'               (contry -> contrie)
                * convert 'ss' at the end into 'e'               (witness -> witnesse)
                * add a 's' at the end is none already there     (nation -> nations)
    '''
    words = value.split(' ')
    if len(words) > 1:
        # We got a phrase. Pluralise each word separately.
        ret = ' '.join([plural(word, count) for word in words])
    else:
        ret = value
        if ret in ['of']: return ret
        if count > 1:
            if ret in ['a', 'an']: return ''
            if ret[-1:] == 'y': 
                ret = ret[:-1] + 'ie'
            if ret[-2:] == 'ss': 
                ret = ret + 'e'
            if not ret[-1:] == 's':
                ret = ret + 's'
    return ret
